version: '3'
services:
    edaweb:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/edaweb
        volumes:
            - /tmp/:/media/ISOs/
            - ./static/:/app/static/
            - ./edaweb.conf:/app/edaweb.conf
        ports:
            - "6969:6969"
        networks:
            - db-network
            - edaweb-net
        external_links:
            - mariadb:mysql
        restart: unless-stopped

    homelab-wiki:
        build:
            context: ./homelab-wiki
            dockerfile: Dockerfile
        image: jwansek/edawiki2
        volumes:
            - ./homelab-wiki/images:/var/www/html/images
            - ./homelab-wiki/LocalSettings.php:/var/www/html/LocalSettings.php
        env_file:
            - ./homelab-wiki/wiki.env
        ports:
            - "6970:80"
        networks:
            - db-network
            - edaweb-net
        external_links:
            - mariadb:mysql
        restart: unless-stopped

networks:
    edaweb-net:
        external:
            name: edaweb-net

    db-network:
        external:
            name: mariadb
