services:
    edaweb:
        build:
            context: .
            dockerfile: Dockerfile
        image: reg.reaweb.uk/edaweb
        volumes:
            - /tmp/:/media/ISOs/
            - ./edaweb/static/:/app/edaweb/static/
            - ./edaweb.conf:/app/edaweb.conf
            - edaweb-tmp:/tmp/
        ports:
            - "6969:6969"
        external_links:
            - mariadb:mysql
            - transmission_1:transmission
        mac_address: 44:c8:09:a7:d0:93 
        networks:
            db-network:
            rr-net:
                ipv4_address: "192.168.23.13"
        restart: unless-stopped

    edaweb_cron:
        build:
            context: .
            dockerfile: Dockerfile_cron
        image: reg.reaweb.uk/edaweb_cron
        volumes:
            - /tmp/:/media/ISOs/
            - ./edaweb/static/:/app/edaweb/static/
            - ./edaweb.conf:/app/edaweb.conf
            - ./edaweb-docker.pem:/keys/docker-key.pem
            - edaweb-tmp:/tmp/
        networks:
            - db-network
        external_links:
            - mariadb:mysql
        restart: unless-stopped

    homelab-wiki:
        build:
            context: ./homelab-wiki
            dockerfile: Dockerfile
        image: reg.reaweb.uk/edawiki2
        volumes:
            - ./homelab-wiki/images:/var/www/html/images
            - ./homelab-wiki/LocalSettings.php:/var/www/html/LocalSettings.php
        env_file:
            - ./homelab-wiki/wiki.env
        ports:
            - "6970:80"
        networks:
            - db-network
        external_links:
            - mariadb:mysql
        restart: unless-stopped

volumes:
    edaweb-tmp:

networks:
    db-network:
        external: true
        name: mariadb

    rr-net:
        external: true
        name: rr-net

