version: '3'
services:
    edaweb:
        build:
            context: .
            dockerfile: Dockerfile
        image: reg.reaweb.uk/edaweb
        volumes:
            - /tmp/:/media/ISOs/
            - ./edaweb/static/:/app/edaweb/static/
            - ./edaweb.conf:/app/edaweb.conf
            - ./edaweb-docker.pem:/keys/docker-key.pem
        ports:
            - "6969:6969"
        networks:
            - db-network
            - edaweb-net
        external_links:
            - mariadb:mysql
        restart: unless-stopped

    homelab-wiki:
        build:
            context: ./homelab-wiki
            dockerfile: Dockerfile
        image: reg.reaweb.uk/edawiki2
        volumes:
            - ./homelab-wiki/images:/var/www/html/images
            - ./homelab-wiki/LocalSettings.php:/var/www/html/LocalSettings.php
        env_file:
            - ./homelab-wiki/wiki.env
        ports:
            - "6970:80"
        networks:
            - db-network
            - edaweb-net
        external_links:
            - mariadb:mysql
        restart: unless-stopped

networks:
    edaweb-net:
        external:
            name: edaweb-net

    db-network:
        external:
            name: mariadb

